name: manga_app
description: Manga app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  html: ^0.15.0
  flutter_bloc: ^8.1.1
  cached_network_image: ^3.2.1
  material_design_icons_flutter: ^5.0.6996

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true